spring.application.name=docprocessor
server.port=8088
bank.statement-expense-categories=GROCERY,PETROL,PERSONAL,SRIDE,ACH,BILL

category.grocery=bigbasket,dmart,reliance smart,blinkit,grocery
category.petrol=iocl,hp petrol,petrol pump,bpcl
category.food=swiggy,zomato,restaurant
category.travel=irctc,uber,ola,makemytrip,travel
category.entertainment=netflix,prime video,
category.bank=ACH,HDFC BANK LTD
category.bills=bills,bill,electricity

#spring.datasource.url=jdbc:h2:mem:statementanalyzerdb;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS statementanalyzerdb
spring.datasource.url=jdbc:h2:file:./statementanalyzerdb;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.show-sql=false
logging.level.org.springframework.jdbc.datasource=DEBUG
logging.level.org.hibernate.SQL=OFF
