package com.asthethi.docprocessor.statementparsers;

import com.asthethi.docprocessor.model.CategoryKeyword;
import com.asthethi.docprocessor.model.FileRequest;
import com.asthethi.docprocessor.model.TransactionResponse;
import com.asthethi.docprocessor.model.entity.TransactionCategory;
import com.asthethi.docprocessor.service.TransactionCategoryService;
import lombok.extern.slf4j.Slf4j;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.io.InputStream;
import java.time.LocalDate;
import java.time.Month;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

@Slf4j
@Component
public class HdfcPdfStatementParser implements StatementFileParser{

    @Value("${bank.statement-expense-categories}")
    private String[] allowedCategoryList;

    private static final Pattern DATE_PATTERN = Pattern.compile("\\b\\d{2}/\\d{2}/\\d{2}\\b");
    private static final Pattern BALANCE_PATTERN =
            Pattern.compile("\\d{1,3}(,\\d{3})*\\.\\d{2}$");

    private static final Pattern TRANSACTION_PATTERN = Pattern.compile("^(\\d{2}/\\d{2}/\\d{2})\\s+(.*?)\\s+(\\S+)\\s+(\\d{2}/\\d{2}/\\d{2})\\s+([\\d,]+\\.\\d{2})\\s+([\\d,]+\\.\\d{2})\\s*$");

    @Autowired
    private TransactionCategoryService transactionCategoryService;


    @Override
    public List<TransactionResponse> parse(FileRequest file) throws IOException {
        return getTransactionsFromPdfFile(file.getDocument());
    }

    private List<TransactionResponse> getTransactionsFromPdfFile(MultipartFile inputFile) throws IOException {

        TransactionResponse currentTrx = null;
        List<TransactionResponse> transactionResponseList = new ArrayList<>();

        try (InputStream inputStream = inputFile.getInputStream();
             PDDocument document = PDDocument.load(inputStream, "71023607")) {

            PDFTextStripper stripper = new PDFTextStripper();
            stripper.setSortByPosition(true);
            String pdfContent = stripper.getText(document);
            String pdfLines[] = pdfContent.split("\\r?\\n");

            Double previousTrx = null;

            for (String line : pdfLines) {
                if (isTransactionRow(line)) {

                    if (currentTrx != null) {
                        transactionResponseList.add(currentTrx);
                    }

                    currentTrx = extractTransaction(line, previousTrx);
                    previousTrx = Double.valueOf(currentTrx.getClosingBalance());


                } else if (currentTrx != null && isTrxNarration(line)) {
                    currentTrx.setNarration(currentTrx.getNarration() + " " + line.trim());
                }
            }

            if (currentTrx != null) {
                transactionResponseList.add(currentTrx);
            }

        }

        for(TransactionResponse transactionResponse : transactionResponseList) {
            this.trxCategoryProvider(transactionResponse);
            log.error("Narration : " + transactionResponse.getNarration() + " trx category : " + transactionResponse.getTransactionCategory() + "**Amount : " + transactionResponse.getDebitAmount());
        }

        return transactionResponseList;
    }

    private void trxCategoryProvider(TransactionResponse transactionResponse) {

        List<TransactionCategory> trxCategories =
                this.transactionCategoryService.findAllCategories();

        for (TransactionCategory trxCategory : trxCategories) {
            for (CategoryKeyword categoryKeyword : trxCategory.getKeywords()) {

                if (transactionResponse.getNarration().toLowerCase().contains(categoryKeyword.getKeyword().toLowerCase())) {
                    transactionResponse.setTransactionCategory(trxCategory.getName().split("\\.")[1]);
                }
            }
        }

        if(Objects.isNull(transactionResponse.getTransactionCategory())) {
            transactionResponse.setTransactionCategory("misc");
        }

    }

    private static boolean isTrxNarration(String line) {
        return !line.contains("Closing Balance") &&
                !line.contains("End of Statement") &&
                !line.contains("Opening Balance") &&
                !line.contains("Dr Count") &&
                !line.contains("Generated On") &&
                !line.contains("STATEMENT SUMMARY") &&
                !line.contains("Generated By") &&
                !line.contains("computer generated statement") &&
                !line.contains("signature") &&
                !line.contains("*Closing balance") &&
                !line.contains("Contents of this statement will be") &&
                !line.contains("this statement") &&
                !line.contains("HDFC BANK LIMITED") &&
                !line.contains("GSTIN number") &&
                !line.contains("Registered Office") &&
                !line.contains("State account") &&
                !line.contains("Statement of account") &&
                !line.contains("Page No") &&
                !line.contains("Account Branch") &&
                !line.contains("Address") &&
                !line.contains("City") &&
                !line.contains("State") &&
                !line.contains("Phone no") &&
                !line.contains("OD Limit") &&
                !line.contains("Email :") &&
                !line.contains("Cust ID :") &&
                !line.contains("Account No :") &&
                !line.contains("A/C Open Date :") &&
                !line.contains("Account Status :") &&
                !line.contains("JOINT HOLDERS :") &&
                !line.contains("RTGS/NEFT IFSC:") &&
                !line.contains("Branch Code :") &&
                !line.contains("Account Type :") &&
                !line.contains("Statement From") &&
                !line.contains("Nomination : Registered") &&
                !line.contains("RAJIV GANDHI INFOTECH PARK,") &&
                !line.contains("NR TATA JOHNSON CONTROLS,");
    }

    private static TransactionResponse extractTransaction(String line, Double previousBalance) {

        Matcher matcher = TRANSACTION_PATTERN.matcher(line.trim());

        if (!matcher.find()) {
            throw new IllegalArgumentException("Invalid transaction row: " + line);
        }

        double amount = Double.parseDouble(matcher.group(5).replace(",", ""));
        Double debitAmount = null;
        Double creditAmount = null;

        double closingBalance = Double.parseDouble(matcher.group(6).replace(",", ""));

        if (previousBalance != null) {
            if (closingBalance < previousBalance) {
                debitAmount = amount;
                creditAmount = 0.0;
            } else {
                creditAmount = amount;
                debitAmount = 0.0;
            }
        }

        return TransactionResponse.builder()
                .transactionDate(matcher.group(1))
                .narration(matcher.group(2))
                .refNumber(matcher.group(3))
                .debitAmount(
                        debitAmount
                )
                .creditAmount(
                        creditAmount
                )
                .closingBalance(matcher.group(6).replace(",", ""))
                .build();
    }

    private static boolean isTransactionRow(String candidate) {
        Matcher dateMatcher = DATE_PATTERN.matcher(candidate);
        int dateCount = 0;

        while (dateMatcher.find()) {
            dateCount++;
        }

        boolean endsWithBalance =
                BALANCE_PATTERN.matcher(candidate.trim()).find();

        return dateCount == 2 && endsWithBalance;
    }
}
