package com.asthethi.docprocessor.statementparsers;

import com.asthethi.docprocessor.constants.ApplicationConstants;
import com.asthethi.docprocessor.model.FileRequest;
import com.asthethi.docprocessor.model.TransactionResponse;
import lombok.extern.slf4j.Slf4j;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

@Slf4j
@Component
public class HdfcPdfStatementParser implements StatementFileParser{

    @Value("${bank.statement-expense-categories}")
    private String[] allowedCategoryList;

    private static final Pattern DATE_PATTERN = Pattern.compile("\\b\\d{2}/\\d{2}/\\d{2}\\b");
    private static final Pattern BALANCE_PATTERN =
            Pattern.compile("\\d{1,3}(,\\d{3})*\\.\\d{2}$");

    private static final Pattern TRANSACTION_PATTERN = Pattern.compile("^(\\d{2}/\\d{2}/\\d{2})\\s+(.*?)\\s+(\\S+)\\s+(\\d{2}/\\d{2}/\\d{2})\\s+([\\d,]+\\.\\d{2})\\s+([\\d,]+\\.\\d{2})\\s*$");


    @Override
    public List<TransactionResponse> parse(FileRequest file) throws IOException {
        return getTransactionsFromPdfFile(file.getDocument());
    }

    private List<TransactionResponse> getTransactionsFromPdfFile(MultipartFile inputFile) throws IOException {

        TransactionResponse currentTrx = null;
        List<TransactionResponse> transactionResponseList = new ArrayList<>();

        try (InputStream inputStream = inputFile.getInputStream();
             PDDocument document = PDDocument.load(inputStream, "71023607")) {

            PDFTextStripper stripper = new PDFTextStripper();
            stripper.setSortByPosition(true);
            String pdfContent = stripper.getText(document);
            String pdfLines[] = pdfContent.split("\\r?\\n");

            for (String line : pdfLines) {
                String transactionCategory = null;
                if (isTransactionRow(line)) {

                    if (currentTrx != null) {
                        transactionResponseList.add(currentTrx);
                    }

                    currentTrx = extractTransaction(line);
                    //start
                    for (String category : allowedCategoryList) {

                        if (category.equals(ApplicationConstants.TRANSACTION_CATEGORY_ACH)) {
                            if (currentTrx.getNarration().toUpperCase().contains(ApplicationConstants.TRANSACTION_CATEGORY_ACH) && currentTrx.getNarration().toUpperCase().toUpperCase().contains(ApplicationConstants.HDFC_BANK_STRING)) {
                                transactionCategory = category;
                            }
                        } else {
                            if (currentTrx.getNarration().toUpperCase().contains(category)) {
                                transactionCategory = category;
                            }
                        }
                    }

                    if (Objects.isNull(transactionCategory)) {
                        transactionCategory = "Misc";
                    }
                    currentTrx.setTransactionCategory(transactionCategory);
                    //end


                } else if (currentTrx != null && isTrxNarration(line)) {
                    currentTrx.setNarration(currentTrx.getNarration() + " " + line.trim());
                }
            }

            if (currentTrx != null) {
                transactionResponseList.add(currentTrx);
            }

        }

//        transactionResponseList.forEach(t -> {
//            System.out.println(t.toString());
//        });
//        System.out.println(transactionResponseList.size());

        return transactionResponseList;
    }

    private static boolean isTrxNarration(String line) {
        return !line.contains("Closing Balance") &&
                !line.contains("End of Statement") &&
                !line.contains("Opening Balance") &&
                !line.contains("Dr Count") &&
                !line.contains("Generated On") &&
                !line.contains("STATEMENT SUMMARY") &&
                !line.contains("Generated By") &&
                !line.contains("computer generated statement") &&
                !line.contains("signature") &&
                !line.contains("*Closing balance") &&
                !line.contains("Contents of this statement will be") &&
                !line.contains("this statement") &&
                !line.contains("HDFC BANK LIMITED") &&
                !line.contains("GSTIN number") &&
                !line.contains("Registered Office") &&
                !line.contains("State account");
    }

    private static TransactionResponse extractTransaction(String line) {

        Matcher matcher = TRANSACTION_PATTERN.matcher(line.trim());

        if (!matcher.find()) {
            throw new IllegalArgumentException("Invalid transaction row: " + line);
        }

        return TransactionResponse.builder()
                .transactionDate(matcher.group(1))
                .narration(matcher.group(2))
                .refNumber(matcher.group(3))
                .debitAmount(
                        matcher.group(5) != null
                                ? Double.valueOf(matcher.group(5).replace(",", ""))
                                : null
                )
                .creditAmount(
                        matcher.group(5) != null
                                ? Double.valueOf(matcher.group(6).replace(",", ""))
                                : null
                )
                .closingBalance(matcher.group(6))
                .build();
    }

    private static boolean isTransactionRow(String candidate) {
        Matcher dateMatcher = DATE_PATTERN.matcher(candidate);
        int dateCount = 0;

        while (dateMatcher.find()) {
            dateCount++;
        }

        boolean endsWithBalance =
                BALANCE_PATTERN.matcher(candidate.trim()).find();

        return dateCount == 2 && endsWithBalance;
    }
}
